Add possibility to revoke group access from the group page
hchevalier/retrospective pull request #179
Opened 2020-11-02 23:18 UTC by jadevdl

![image](https://user-images.githubusercontent.com/37371042/97929388-6187e680-1d69-11eb-8ace-2387de0fc4ea.png)
![image](https://thumbs.gfycat.com/TimelyEnlightenedGrouse-size_restricted.gif)

* Remove button is displayed on hover on the member name
* If there are multiple users, when removing one, it updates the title "Group members (2) --> (1)"
* If there was only one user, when removing the last one it deletes the group and redirects to the "/groups" page

**I don't know why, when running my test locally, sometimes it fails, sometimes it works, any idea why?**
* I wanted to maybe add an id on the "remove" button, to help testing, but I didn't succeed doing it

2020-11-03 12:32 UTC, jadevdl commented on app/javascript/components/GroupDetails.js
> +        `Are you sure you want to remove this user from the group ${group.name}?`
Of course, I make the change :)

2020-11-03 12:35 UTC, jadevdl commented on app/javascript/components/GroupDetails.js
> +  	window.location.href = "/groups";
What are your settings/vscode extension for the indentation? When I'm trying to automatically format my code, it adds semicolon everywhere and adds a lot of indentation everywhere

2020-11-03 13:11 UTC, jadevdl commented on app/javascript/components/App.js
> +    return <GroupDetails id={params.groupId} history={history}/>
I find it weird to give as props the `history` since nowhere else it's needed. But without, it doesn't work. How can I do?

2020-11-03 13:41 UTC, hchevalier commented on app/javascript/components/App.js
> +    return <GroupDetails id={params.groupId} history={history}/>
Everything between `<Router>` and `<Router />` can use the `withRouter` high order component (HOC).

`App` component is inside the router (you can see that the default export is `export default AppWithRouter`), so any component rendered from here is eligible. Any component that uses the withRouter HOC receives an `history` prop, you won't have to pass it explicitly :)

You can see an example of usage in `RetrospectiveContainer` component

2020-11-03 19:59 UTC, hchevalier commented on app/javascript/components/GroupDetails.js
> +  	window.location.href = "/groups";
I don't think I'm using a specific extension, my VSCode install is pretty bare.

Might be due to the one you use actually :)

2020-11-03 21:30 UTC, jadevdl commented on app/javascript/components/App.js
> +    return <GroupDetails id={params.groupId} history={history}/>
awesome it works great, thanks!

2020-11-03 22:32 UTC, jadevdl commented on app/javascript/components/GroupDetails.scss
> +    float: right;
I added tailwind class to avoid `float: right` css :)
I tried `onMouseEnter/onMouseLeave` + state, it worked but I didn't manage to test it easily with the `find('.class').hover`. I leave it for later :)

2020-11-03 23:49 UTC, jadevdl commented on app/controllers/api/group_accesses_controller.rb
> +  def update
I made the changes :) Please let me know if it's done properly, as I am not sure about several things:
* naming variables explicit enough?
* `def other_account?` method useful or a `if else` condition would have been better?
* errors when not finding account/group_access are not handled, is it needed? how?

commit: https://github.com/hchevalier/retrospective/pull/179/commits/96546f44e425c2edcc2dd81dc5f40d24b2388075

(and still the indentation problem, for my very last commit I will make sure to clean the indentation)

2020-11-03 23:50 UTC, hchevalier commented on app/javascript/components/GroupDetails.js
> +	const removeMemberFromGroup = (account) => {
Your indentation is really broken 😅

Also, it's being late, no? 😂

2020-11-03 23:55 UTC, jadevdl commented on app/javascript/components/GroupDetails.js
> +	const removeMemberFromGroup = (account) => {
it drives me crazy 🤯
yes I'm going to sleep haha, see you later in the day haha

2020-11-05 07:00 UTC, hchevalier requested changes
💪

2020-11-05 23:50 UTC, jadevdl commented on test/integration/group_accesses_test.rb
> +    assert_text 'REMOVE', count: 1
not sure it's enough: there's no check that the "REMOVE" is actually for the other member and not for the current account :/ I don't know how to do.. maybe to add an id to the "remove" button that could allow linking to the member?

2020-11-05 23:53 UTC, jadevdl commented on app/javascript/components/GroupDetails.scss
> +}
I removed the CSS with the hover button for now. I'll add it back at the end, because it was blocking me for testing and I want to focus on this later :)

2020-11-05 23:53 UTC, jadevdl commented on app/javascript/components/GroupDetails.js
> +                          <span className='remove-button'>
done!

2020-11-06 21:25 UTC, jadevdl commented on app/javascript/components/GroupDetails.js
> +        if (group.members.length === 1) {
It seems I don't need to call `refreshGroup`. But how can I be sure the `group_members` value has changed?
I have also the flaky when rendering the Card component that displays as title "Group members `(${group.members.length})`"

2020-11-06 23:33 UTC, jadevdl commented on app/javascript/components/GroupDetails.js
> +const GroupsDetails = ({ id, history }) => {
actually I don't need `history` anymore. I used it to redirect to the groups page if everyone left the group, but since the creator of the group cannot revoke it's own access from there, it's no more needed.

2020-11-06 23:37 UTC, jadevdl commented on app/javascript/components/GroupsList.js
> +      destroy({ url: `/api/account/${currentAccount.publicId}/group_accesses/${groupToRevokeFrom.id}` })
alright!

2020-11-06 23:38 UTC, jadevdl commented on app/controllers/api/group_accesses_controller.rb
> +    revoke_access(group_access)
still WIP ;)

2020-11-06 23:39 UTC, jadevdl commented on app/javascript/components/App.js
> +    return <GroupDetails id={params.groupId }/>
```suggestion
    return <GroupDetails id={params.groupId} />
```

2020-11-06 23:43 UTC, jadevdl commented on test/integration/group_accesses_test.rb
> +    assert_not_nil group.group_accesses.find_by(account_id: other_account.id).revoked_at
this test doesn't pass. If I put a binding pry before the `assert_not_nil` the `revoked_at` value is yet correctly set

2020-11-08 00:42 UTC, jadevdl commented on app/controllers/api/group_accesses_controller.rb
> +    group_access = GroupAccess.find_by(group_id: params[:id], account_id: account.id)
How can an account access to a group he doesn't belong? 
The group will not be displayed in his groups page and we cannot do something like this in the test: `delete "/api/group_accesses/#{group.id}", params: { account: other_account }` (I get a `ActionController::InvalidAuthenticityToken` ) when the current_account is not in the group and tries to remove other_account which is.

2020-11-08 10:35 UTC, hchevalier commented on app/controllers/api/group_accesses_controller.rb
> +    group_access = GroupAccess.find_by(group_id: params[:id], account_id: account.id)
The `InvalidAuthenticityToken` is due to having no CSRF token being sent. That call should be possible from a JS console though:
```
const csrfToken = document.querySelector('[name=csrf-token]').content
const formData = new FormData()
formData.append('account', the_public_id_of_another_user)
fetch('https://docto-retrospective.herokuapp.com/api/group_accesses/a_group_id_this_user_is_part_of', {
  method: 'DELETE',
  body: formData,
  headers: new Headers({
    'Content-Type': 'application/json',
    'X-CSRF-TOKEN': csrfToken
  })
})
```

This is why we want to check that current user also has sufficient access to the target group ;)

2020-11-09 00:01 UTC, jadevdl commented on config/routes.rb
> +      resources :accounts, only: %i(destroy), controller: 'group_accesses'
```suggestion
      resources :accounts, only: %i[destroy], controller: 'group_accesses'
```

I don't understand, on my local dev it's `(destroy)` and there are parenthesis everywhere, but on here github they are all replaced by `[...]`?

2020-11-09 01:03 UTC, hchevalier commented on app/controllers/api/group_accesses_controller.rb
> +    return render json: 'record not found for delete', status: :not_found
This should only be possible when `current_account.groups.find(params[:group_id])` fails (because your other queries use find_by, which returns nil without raising exceptions

You should use `find_by` on the first check and return a `forbidden` error if `group` is nil

2020-11-09 01:05 UTC, hchevalier commented on app/javascript/components/GroupDetails.js
> +                          {currentAccount.publicId !== account.publicId ? (
`currentAccount.publicId !== account.publicId &&` allows to avoid a ternary (you won't have the ` : null` part)

2020-11-09 01:07 UTC, hchevalier commented on app/javascript/components/GroupsList.js
> +                          onClick={(event) => { event.preventDefault(); handleLeaveGroup(groupAccess, group) }}>
`group` is a key of `groupAccess` (you know because it's destructurated here: `const { group } = groupAccess`)

so you don't have to pass it as an argument to `handleLeaveGroup`, you'll be able to do `groupAccessToRevoke.group` from there ;)

2020-11-09 01:09 UTC, hchevalier commented on config/routes.rb
> +      resources :accounts, only: %i(destroy), controller: 'group_accesses'
I added Rubocop and ESLint checks to the CI (and fixed aaaaaall the existing offenses) ;)

Brackets were Rubocop's default characters for array literals, I found it better than parenthesis because hey, it's an array after all :)

2020-11-09 01:12 UTC, hchevalier commented on test/controllers/group_accesses_controller_test.rb
> +  end
You should check each error distinctly:
- current_account does not have access to the group xxx OR group xxx does not exist (your first '000', but already tested in previous test actually)
- no account with public ID yyy found in the group (the second '000')

2020-11-09 01:15 UTC, hchevalier commented on test/integration/group_accesses_test.rb
> +    assert_text 'REMOVE', count: 1
You could sort `accounts_without_revoked` in order of `group_accesses`creation (that can be achieved directly in the lambda received by `has_many :accounts_without_revoked`)

Then you can do `within find_all('li').first` or `within find_all('li').last` around you assert_text to make sure 'REMOVE' is in the correct one

2020-11-09 01:17 UTC, hchevalier commented on test/integration/group_accesses_test.rb
> +    assert_text 'REMOVE', count: 1
You can also have a group with a single person (the current user) and assert the button is not here, that would be a sufficient proof ;)

2020-11-09 01:17 UTC, hchevalier reviewed
Great, nearly done! 🤩

2020-11-09 21:04 UTC, jadevdl commented on test/controllers/group_accesses_controller_test.rb
> +  end
I'll split then! I wasn't sure it was important to test that, but I was wrong :)

2020-11-09 21:06 UTC, jadevdl commented on app/javascript/components/GroupsList.js
> +                          onClick={(event) => { event.preventDefault(); handleLeaveGroup(groupAccess, group) }}>
oh right 😅 just like it was before

2020-11-09 21:08 UTC, jadevdl commented on app/javascript/components/GroupDetails.js
> +                          {currentAccount.publicId !== account.publicId ? (
good to know!

2020-11-09 21:18 UTC, jadevdl commented on app/controllers/api/group_accesses_controller.rb
> +    return render json: 'record not found for delete', status: :not_found
2 questions:
* why not doing the `rescue` with `.find`? isn't it cleaner to raise an exception?
* I'm not sure if I need to return a status :not_found or : forbidden for the 3 kind of errors

2020-11-09 22:01 UTC, hchevalier commented on app/controllers/api/group_accesses_controller.rb
> +    return render json: 'record not found for delete', status: :not_found
Exceptions have a performance cost in Ruby:
https://www.honeybadger.io/blog/benchmarking-exceptions-in-ruby-yep-theyre-slow/ or http://technicaldebt.com/the-cost-of-using-rubys-rescue-as-logic/ (for example, there are other benchmarks)

Even if the cost for 1 exception handling is ridiculous, what's important is (I'll paraphrase some article here):

> Exceptions should not be expected and, in some circumstances, an if can be much more convenient, or at least, efficient.

> exceptions should not be part of the regular application flow. This shouldn't prevent you to use them to handle unexpected situations and exception performance shouldn't be a big deal in this case.

> avoid using exceptions in place of conditional statements to handle not exceptional situations

2020-11-09 22:06 UTC, hchevalier commented on app/controllers/api/group_accesses_controller.rb
> +    return render json: 'record not found for delete', status: :not_found
Regarding the status, I'd use 403 for ressources which the user cannot access to (another account for example, or a group he's not part of), and 404 when the resource does not exist.

I'd raise a 403 here, because were not expecting the user to grant an incorrect group (the UI will never suggest that, if it happens it can only be caused by manual interventions)

2020-11-09 22:21 UTC, jadevdl commented on test/integration/group_accesses_test.rb
> +    assert_text 'REMOVE', count: 1
I found this: `find('li', text: 'Other member')` which works perfectly to find an element using the text, exactly what I needed :)

2020-11-09 22:22 UTC, jadevdl commented on config/routes.rb
> +      resources :accounts, only: %i(destroy), controller: 'group_accesses'
great!! yes it makes sense haha

2020-11-09 22:36 UTC, jadevdl commented on app/controllers/api/group_accesses_controller.rb
> +    return render json: 'record not found for delete', status: :not_found
Okay thanks for the explanation! That's clear.

That's weird, when I remove the rescue error and I put:

    group = current_account.groups.find_by(id: params[:group_id])
    return render(json: { status: :forbidden }) unless group

all my test fail because it returns a `<200: OK>` even if `group` is `nil`

Any idea why?

2020-11-09 22:49 UTC, hchevalier commented on app/controllers/api/group_accesses_controller.rb
> +    return render json: 'record not found for delete', status: :not_found
Yes, the `{ status: :forbidden }` you send is plain json (it's just a key and a value), it's does not correspond to the HTTP status code you're returning

You can use `render(json: { error: 'My error message' }, status: :forbidden)` for that

2020-11-09 23:04 UTC, jadevdl commented on app/controllers/api/group_accesses_controller.rb
> +    return render json: 'record not found for delete', status: :not_found
ah! perfect! thank you 😇

2020-11-09 23:15 UTC, jadevdl commented
I tried to add the hover to display the REMOVE button but there was another weird behavior when testing it. I gave up sorry.. maybe it could be an improvement in the future

2020-11-09 23:20 UTC, hchevalier commented on app/controllers/api/group_accesses_controller.rb
> +    render json: current_account.accessible_groups.map(&:as_short_json)
You're triggering unnecessary SQL queries here, you should just return a 200 (default http status) with an empty payload ;)

2020-11-09 23:29 UTC, hchevalier reviewed
Last **really** minor changes and we're good to go 🥳

Also, beware, you versioned a `test/controllers/.keep` file that should not be indexed ;)

2020-11-09 23:29 UTC, hchevalier commented on app/controllers/api/group_accesses_controller.rb
> +    return render(json: { error: 'Account does not have access to this group.' }, status: :forbidden) unless group_access
This one would be a 404, the person you want to revoke access does not have any access in the group ;)

2020-11-09 23:29 UTC, hchevalier commented on app/javascript/components/GroupDetails.js
> +                            onClick={(event) => { event.preventDefault(); revokeAccessFromGroup(account) }}>
```suggestion
                              className='bg-red-200 text-red-700 text-xxs inline-flex items-center font-bold leading-sm uppercase px-3 py-1 rounded-full'
                              onClick={(event) => { event.preventDefault(); revokeAccessFromGroup(account) }}>
```

2020-11-09 23:29 UTC, hchevalier commented on app/javascript/components/GroupsList.js
> +
Beware, `currentAccount` is fetched asynchronously.

The "LEAVE" button should only appear once the account is fetched (that will make the integration test easier, the perfect thing would have be to disable the button until account is fetched but that's not a problem)

2020-11-09 23:29 UTC, hchevalier commented on test/controllers/group_accesses_controller_test.rb
> +  end
If it does not exist, it's not in the group, I'd remove this one (already covered  by the test just below) ;)

2020-11-11 14:04 UTC, jadevdl commented on app/controllers/api/group_accesses_controller.rb
> +    render json: current_account.accessible_groups.map(&:as_short_json)
oh right!

2020-11-11 14:12 UTC, jadevdl commented on app/controllers/api/group_accesses_controller.rb
> +    return render(json: { error: 'Account does not have access to this group.' }, status: :forbidden) unless group_access
I change. I thought it was a forbidden since we do have the account, but it is forbidden to remove the account from the group if he doesn't have any access. But I see your point, the group_access is not found!

2020-11-11 14:50 UTC, jadevdl commented on app/controllers/api/group_accesses_controller.rb
> +    return render(json: { error: 'Account does not have access to this group.' }, status: :forbidden) unless group_access
It seems that this case was not covered by test. I tried to add it but there's something I'm not sure to understand.
If an account is in the group, but we revoke his access. The account should be still in the group, right? But is there some dependent destroy to remove the account from the account too? I couldn't find any in the group_access model

2020-11-11 14:57 UTC, jadevdl commented on test/controllers/group_accesses_controller_test.rb
> +  end
that's right :)

2020-11-11 15:09 UTC, hchevalier commented on test/controllers/group_accesses_controller_test.rb
> +end
Duplicated test

2020-11-11 17:35 UTC, jadevdl commented on test/controllers/group_accesses_controller_test.rb
> +end
ooops

2020-11-11 17:38 UTC, jadevdl commented on app/controllers/api/group_accesses_controller.rb
> +    return render(json: { error: 'Account does not have access to this group.' }, status: :forbidden) unless group_access
Okay!

2020-11-11 17:48 UTC, hchevalier approved these changes
Great! Congratulations ;)

2020-11-11 17:49 UTC, merged