add Daki
hchevalier/retrospective pull request #304
Opened 2021-05-08 10:26 UTC by coralieco

![image](https://user-images.githubusercontent.com/22852543/117535919-7f742380-aff8-11eb-84b9-8ba9af2a4d18.png)

2021-05-08 13:07 UTC, hchevalier requested changes
Really minor feedback to keep some consistency between icons and zone colors ;)

2021-05-08 13:07 UTC, hchevalier commented on app/javascript/components/Icon.js
> +import Idea from 'images/idea.png'
Could you move these above the `import './Icon.scss'` please? :)

2021-05-08 13:07 UTC, hchevalier commented on app/javascript/components/retrospectives/Daki.scss
> +  }
Could you just find colors that better match the icon ones for Add & Keep?

Also, the "Add" icon seems to have a different style (the 3 others have kind of an "ink" feeling).

Last question, did you design the icons? If yes, kudos! If not and you find them on a specific website, could you update the README to credit the authors in the dedicated section?

Thanks a lot!

2021-05-08 13:31 UTC, coralieco commented on app/javascript/components/retrospectives/Daki.scss
> +  }
Yes sure, I was thinking that my color choices was not really "accessible". I will choose color with more contrasts, sorry about that. 

I didn't design the icons, I use flaticon! Of course I'll update the credits.

2021-05-10 06:40 UTC, coralieco commented on app/javascript/components/retrospectives/Daki.scss
> +  }
I changed the colors to better fit the icons. All combinaisons are accessible. What do you think? (the blue button "I'm done" could be improved for accessibility in later PRs)

![image](https://user-images.githubusercontent.com/22852543/117616263-2bd61700-b16b-11eb-96cb-df9e3161d96c.png)

2021-05-10 06:56 UTC, coralieco commented on app/javascript/components/retrospectives/Daki.scss
> +  }
Changed the add icon so it would be more ink-ed-styled

![image](https://user-images.githubusercontent.com/22852543/117617940-8cfeea00-b16d-11eb-8d5d-4050687eab10.png)

2021-05-10 07:01 UTC, coralieco commented on app/javascript/components/retrospectives/Daki.scss
> +  }
(PS: I left the green color for the add button, I find green and yellow  to fit quite well but I can change if you prefer)

2021-05-14 20:52 UTC, hchevalier approved these changes

2021-05-14 20:53 UTC, merged